vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/uploads/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       artwork_image:
           uri_prefix: /uploads/artworkImages
           upload_destination: '%kernel.project_dir%/public/uploads/artworkImages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
